package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type InvoiceStatus string

const (
	// InvoiceStatusDraft: hóa đơn được cron tự động tạo đầu tháng cho các phòng
	// đang có hợp đồng active, CHƯA có chỉ số điện/nước thật -> chưa tính vào
	// total_amount thật, chưa hiển thị cho tenant, chưa cho phép thanh toán.
	// Manager phải xem lại, điền chỉ số điện/nước rồi "xác nhận" (ConfirmDraftInvoice)
	// để chuyển sang "unpaid" thì hóa đơn mới chính thức có hiệu lực.
	InvoiceStatusDraft   InvoiceStatus = "draft"
	InvoiceStatusUnpaid  InvoiceStatus = "unpaid"
	InvoiceStatusPartial InvoiceStatus = "partial"
	InvoiceStatusPaid    InvoiceStatus = "paid"
	// InvoiceStatusCancelled: hóa đơn tạo sai/hủy bỏ. Chỉ có thể chuyển sang
	// trạng thái này nếu chưa ghi nhận thanh toán nào (paid_amount == 0), để
	// không làm mất dấu vết dòng tiền đã thu. Hóa đơn cancelled không tính vào
	// check trùng phòng/tháng khi tạo hóa đơn mới.
	InvoiceStatusCancelled InvoiceStatus = "cancelled"
)

// ValidInvoiceStatuses liệt kê toàn bộ giá trị hợp lệ, dùng để validate input.
var ValidInvoiceStatuses = []InvoiceStatus{InvoiceStatusDraft, InvoiceStatusUnpaid, InvoiceStatusPartial, InvoiceStatusPaid, InvoiceStatusCancelled}

// IsValid kiểm tra InvoiceStatus có phải là 1 trong các giá trị enum hợp lệ không.
func (s InvoiceStatus) IsValid() bool {
	switch s {
	case InvoiceStatusDraft, InvoiceStatusUnpaid, InvoiceStatusPartial, InvoiceStatusPaid, InvoiceStatusCancelled:
		return true
	}
	return false
}

// Invoice = hóa đơn của 1 phòng trong 1 tháng, gồm tiền nhà + điện + nước
type Invoice struct {
	ID     primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	RoomID primitive.ObjectID `bson:"room_id" json:"room_id"`

	// TenantID: tenant "đại diện" (người đầu tiên trong phòng lúc tạo hóa đơn).
	// Giữ lại để tương thích ngược, KHÔNG dùng field này để check quyền xem nữa.
	TenantID primitive.ObjectID `bson:"tenant_id" json:"tenant_id"`

	// TenantIDs: snapshot toàn bộ tenant đang ở phòng tại thời điểm tạo hóa đơn.
	// Dùng để mọi người ở ghép trong phòng đều xem được hóa đơn/lịch sử thanh
	// toán của phòng mình, không chỉ riêng người "đại diện". Hóa đơn tạo trước
	// khi có field này sẽ rỗng -> handler fallback so khớp với TenantID.
	TenantIDs []primitive.ObjectID `bson:"tenant_ids,omitempty" json:"tenant_ids,omitempty"`

	Month int `bson:"month" json:"month"` // 1-12
	Year  int `bson:"year" json:"year"`

	RentAmount float64 `bson:"rent_amount" json:"rent_amount"`

	ElectricOld    float64 `bson:"electric_old" json:"electric_old"` // chỉ số cũ
	ElectricNew    float64 `bson:"electric_new" json:"electric_new"` // chỉ số mới
	ElectricPrice  float64 `bson:"electric_price" json:"electric_price"`
	ElectricAmount float64 `bson:"electric_amount" json:"electric_amount"` // = (new-old)*price

	WaterOld    float64 `bson:"water_old" json:"water_old"`
	WaterNew    float64 `bson:"water_new" json:"water_new"`
	WaterPrice  float64 `bson:"water_price" json:"water_price"`
	WaterAmount float64 `bson:"water_amount" json:"water_amount"`

	OtherFees float64 `bson:"other_fees,omitempty" json:"other_fees,omitempty"` // phí khác: rác, internet...
	OtherNote string  `bson:"other_note,omitempty" json:"other_note,omitempty"`

	Occupants              int     `bson:"occupants" json:"occupants"`                                 // số người ở phòng tại thời điểm chốt hóa đơn
	ManagementFeePerPerson float64 `bson:"management_fee_per_person" json:"management_fee_per_person"` // đơn giá phí quản lý/người dùng để tính tháng này
	ManagementFeeAmount    float64 `bson:"management_fee_amount" json:"management_fee_amount"`         // = occupants * management_fee_per_person

	TotalAmount float64       `bson:"total_amount" json:"total_amount"`
	PaidAmount  float64       `bson:"paid_amount" json:"paid_amount"`
	Status      InvoiceStatus `bson:"status" json:"status"`

	// PaymentRefCode: mã tham chiếu duy nhất dùng làm nội dung chuyển khoản,
	// giúp webhook (SePay...) tự động đối soát giao dịch về đúng hóa đơn.
	PaymentRefCode string `bson:"payment_ref_code,omitempty" json:"payment_ref_code,omitempty"`

	// IsAutoGenerated: true nếu hóa đơn này do cron đầu tháng tự động tạo
	// (dạng "draft"), false nếu manager tự tay tạo qua CreateInvoice.
	IsAutoGenerated bool `bson:"is_auto_generated,omitempty" json:"is_auto_generated,omitempty"`

	// Overdue: cờ đánh dấu hóa đơn đã quá hạn (unpaid/partial mà due_date đã
	// qua), do cron quét hàng ngày cập nhật (xem handlers.RunOverdueInvoiceCheck).
	// Không cần tự tính lại ở FE - chỉ cần đọc field này hoặc lọc status=overdue.
	Overdue bool `bson:"overdue,omitempty" json:"overdue,omitempty"`

	DueDate   time.Time `bson:"due_date" json:"due_date"`
	CreatedAt time.Time `bson:"created_at" json:"created_at"`
	UpdatedAt time.Time `bson:"updated_at" json:"updated_at"`
}
