// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "RUMA Support",
            "email": "support@ruma.local"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/change-password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Đổi mật khẩu cho user đang đăng nhập.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Đổi mật khẩu",
                "parameters": [
                    {
                        "description": "Mật khẩu cũ và mới",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Đăng nhập chung cho cả Manager và Tenant, trả về JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Thông tin đăng nhập",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lấy thông tin user đang đăng nhập (từ JWT token).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Lấy thông tin bản thân",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager xem tất cả (lọc được theo room_id, status). Tenant chỉ xem hợp đồng của mình.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Danh sách hợp đồng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lọc theo phòng",
                        "name": "room_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Lọc theo trạng thái (active|ended|terminated|cancelled)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager tạo hợp đồng thuê cho 1 nhóm tenant vào 1 phòng: gán\ntenant vào phòng, khởi tạo thông tin cọc/thời hạn. Phòng đích\nkhông được có hợp đồng \"active\" khác, và tenant không được\nđang thuộc phòng nào khác.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Tạo hợp đồng thuê mới (checkin)",
                "parameters": [
                    {
                        "description": "Thông tin hợp đồng",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createContractRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Xem chi tiết hợp đồng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sửa ghi chú/giá thuê/tiền cọc thỏa thuận (deposit_amount chỉ sửa được khi chưa thu cọc).\nĐể đổi ngày hết hạn, dùng endpoint gia hạn (/extend). Để kết thúc hợp đồng, dùng /checkout.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Cập nhật thông tin hợp đồng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dữ liệu cập nhật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateContractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Chỉ hủy được khi hợp đồng đang active VÀ chưa thu đồng cọc nào.\nNếu đã thu cọc, phải dùng /checkout để hoàn/giữ cọc đúng quy trình.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Hủy hợp đồng (ký nhầm / đổi ý, chưa thu cọc)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/checkout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager xác nhận tenant trả phòng: đóng hợp đồng (ended nếu tới/qua\nhạn, terminated nếu chấm dứt sớm), hoàn cọc theo refund_amount (có thể\ngiữ lại 1 phần), gỡ toàn bộ tenant của hợp đồng khỏi phòng.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Checkout / kết thúc hợp đồng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin checkout",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.checkoutContractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/collect-deposit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager ghi nhận 1 lần thu cọc (có thể thu nhiều lần cho tới khi đủ deposit_amount).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Thu tiền cọc",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin thu cọc",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.collectDepositRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/deposit-transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Lịch sử thu/hoàn/giữ cọc của 1 hợp đồng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/extend": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager gia hạn hợp đồng đang active, đẩy end_date ra xa hơn.\nLịch sử gia hạn được lưu lại trong renewals để tra cứu.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Gia hạn hợp đồng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin gia hạn",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.extendContractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/tenants": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager thêm 1 tenant có sẵn vào hợp đồng đang active (ở ghép\ngiữa chừng), gán luôn tenant đó vào phòng của hợp đồng. Tenant\nphải chưa thuộc phòng nào khác và chưa đứng tên hợp đồng active nào khác.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Thêm 1 người ở ghép vào hợp đồng đang active",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tenant cần thêm",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.addTenantToContractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contracts/{id}/tenants/{tenantId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager gỡ 1 tenant khỏi hợp đồng đang active (những tenant\nkhác vẫn ở lại, hợp đồng vẫn active). Không cho gỡ nếu đây là\ntenant cuối cùng của hợp đồng - trường hợp đó phải dùng\n/checkout hoặc /cancel để đóng hẳn hợp đồng.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Gỡ 1 người ở ghép khỏi hợp đồng đang active",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Contract ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tenant ID cần gỡ",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/invoices": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager xem tất cả, Tenant chỉ xem hóa đơn của mình. Có thể lọc theo room_id, status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Danh sách hóa đơn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lọc theo phòng",
                        "name": "room_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Lọc theo trạng thái",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager tạo hóa đơn cho 1 phòng trong 1 tháng.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Tạo hóa đơn",
                "parameters": [
                    {
                        "description": "Thông tin hóa đơn",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createInvoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/invoices/generate-draft": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager chạy tay (hoặc để cron tự chạy đầu mỗi tháng) để tạo\nhóa đơn \"draft\" cho mọi phòng có hợp đồng active chưa có hóa\nđơn tháng này. Tiền phòng/phí quản lý đã tự suy ra sẵn, chỉ còn\nthiếu chỉ số điện/nước - dùng ConfirmDraftInvoice để hoàn tất.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Tạo hóa đơn nháp cho toàn bộ phòng đang có hợp đồng active",
                "parameters": [
                    {
                        "description": "Tháng/năm cần tạo (mặc định tháng hiện tại)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.generateDraftInvoicesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/invoices/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Xem thông tin chi tiết một hóa đơn theo ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Xem chi tiết hóa đơn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invoice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager sửa hóa đơn tạo sai. CHỈ cho phép sửa khi hóa đơn chưa\nghi nhận thanh toán nào (paid_amount == 0) - nếu đã có thanh\ntoán, hãy hủy hóa đơn (cancel) rồi tạo lại để tránh làm lệch\nsố tiền đã thu.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Sửa hóa đơn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invoice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dữ liệu cập nhật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateInvoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/invoices/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager hủy 1 hóa đơn tạo sai. CHỈ cho phép hủy khi chưa ghi\nnhận thanh toán nào (paid_amount == 0), để không mất dấu vết\ndòng tiền đã thu. Hóa đơn hủy vẫn được giữ lại (soft-cancel) để\ntra cứu, không tính vào check trùng phòng/tháng khi tạo hóa đơn mới.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Hủy hóa đơn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invoice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/invoices/{id}/confirm": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager điền chỉ số điện/nước thật cho hóa đơn do cron tự động\ntạo (status=draft), hệ thống tính lại total_amount và chuyển\nhóa đơn sang \"unpaid\" - từ lúc này tenant mới thấy được hóa đơn.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Xác nhận hóa đơn nháp (điền chỉ số điện/nước)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invoice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Chỉ số điện/nước thật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.confirmDraftInvoiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/invoices/{id}/qr-code": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sinh mã VietQR (chuyển khoản ngân hàng) với số tiền = số tiền còn lại của hóa đơn,\nnội dung chuyển khoản tự động điền theo mã phòng + tháng/năm.\nCần cấu hình BANK_ID, BANK_ACCOUNT_NO, BANK_ACCOUNT_NAME trong biến môi trường.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Invoices"
                ],
                "summary": "Lấy mã QR chuyển khoản cho hóa đơn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invoice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager xem tất cả, Tenant chỉ xem của mình. Có thể lọc theo invoice_id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Danh sách thanh toán",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lọc theo hóa đơn",
                        "name": "invoice_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager ghi nhận 1 lần thanh toán cho hóa đơn.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Ghi nhận thanh toán",
                "parameters": [
                    {
                        "description": "Thông tin thanh toán",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/payments/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager sửa lại 1 payment ghi nhận nhầm (sai số tiền/phương thức/ngày).\nInvoice liên quan sẽ được tính lại paid_amount/status từ tổng\ncác payment thực tế còn lại. Không cho sửa payment tự động qua webhook\n(is_auto_confirmed) vì phải khớp với giao dịch ngân hàng thật.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Sửa 1 lần thanh toán",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dữ liệu cập nhật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager xóa 1 payment ghi nhận nhầm. Invoice liên quan sẽ được\ntính lại paid_amount/status từ tổng các payment thực tế còn lại.\nKhông cho xóa payment tự động qua webhook (is_auto_confirmed) -\ndữ liệu đó phải khớp với giao dịch ngân hàng thật, không nên xóa tay.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Xóa 1 lần thanh toán",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/reports/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager xem nhanh doanh thu đã lập/đã thu trong 1 tháng, tỷ lệ\nlấp đầy phòng hiện tại, và danh sách công nợ (hóa đơn chưa thu đủ).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Báo cáo tổng hợp (doanh thu / tỷ lệ lấp đầy / công nợ)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tháng (mặc định tháng hiện tại)",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Năm (mặc định năm hiện tại)",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/rooms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Lấy danh sách phòng",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Tạo phòng mới",
                "parameters": [
                    {
                        "description": "Thông tin phòng",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/rooms/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Xem chi tiết một phòng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID của phòng",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Cập nhật thông tin phòng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID của phòng",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dữ liệu cập nhật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Xóa phòng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID của phòng",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/rooms/{id}/checkout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rooms"
                ],
                "summary": "Trả phòng",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/system/run-daily-jobs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Chạy ngay lập tức các job mà bình thường cron chạy tự động lúc\nnửa đêm: quét hóa đơn quá hạn, quét hợp đồng sắp hết hạn. Hữu\ních để kiểm tra ngay không cần chờ tới giờ cron hoặc qua ngày mới.\nKhông bao gồm tạo hóa đơn nháp đầu tháng - dùng riêng\nPOST /api/invoices/generate-draft cho việc đó.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Chạy tay các cron job hàng ngày (test/vận hành)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager xem danh sách tất cả tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Danh sách người thuê",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Chỉ Manager được tạo tài khoản Tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Tạo tài khoản người thuê",
                "parameters": [
                    {
                        "description": "Thông tin người thuê",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.createTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager xem thông tin chi tiết một tenant theo ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Xem chi tiết người thuê",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manager cập nhật thông tin tenant.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Cập nhật người thuê",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin cập nhật",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateTenantRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/users/{id}/room": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Gán/đổi phòng cho người thuê có sẵn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Phòng muốn gán",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.assignRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Trả phòng cho 1 người thuê cụ thể",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/webhooks/sepay": {
            "post": {
                "description": "Endpoint public (không cần JWT) để SePay gọi đến mỗi khi có biến động số dư.\nXác thực bằng header Authorization: Apikey \u003cSEPAY_WEBHOOK_API_KEY\u003e.\nTự động đối soát theo mã tham chiếu trong nội dung chuyển khoản và ghi nhận thanh toán.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Webhook nhận báo giao dịch từ SePay",
                "parameters": [
                    {
                        "description": "Payload từ SePay",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.sepayWebhookPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.addTenantToContractRequest": {
            "type": "object",
            "required": [
                "tenant_id"
            ],
            "properties": {
                "tenant_id": {
                    "type": "string"
                }
            }
        },
        "handlers.assignRoomRequest": {
            "type": "object",
            "required": [
                "room_id"
            ],
            "properties": {
                "room_id": {
                    "type": "string"
                }
            }
        },
        "handlers.changePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "old_password": {
                    "type": "string",
                    "x-order": "0"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 6,
                    "x-order": "1"
                }
            }
        },
        "handlers.checkoutContractRequest": {
            "type": "object",
            "properties": {
                "actual_end_date": {
                    "description": "ActualEndDate: để trống -\u003e dùng thời điểm hiện tại. Nếu có, định dạng \"YYYY-MM-DD\".",
                    "type": "string"
                },
                "deduction_note": {
                    "description": "DeductionNote: lý do trừ cọc (nếu refund_amount \u003c số cọc đang giữ).",
                    "type": "string"
                },
                "reason": {
                    "description": "Reason: lý do chấm dứt hợp đồng nói chung (hết hạn, vi phạm, thỏa thuận...).",
                    "type": "string"
                },
                "refund_amount": {
                    "description": "RefundAmount: số tiền cọc thực trả lại cho tenant (có thể \u003c số đã thu\nnếu trừ phí hư hỏng/nợ tiền phòng...). Bắt buộc khai báo rõ ràng,\nkhông tự động suy luận, để manager luôn kiểm soát số tiền hoàn.",
                    "type": "number",
                    "minimum": 0
                },
                "refund_method": {
                    "$ref": "#/definitions/models.PaymentMethod"
                }
            }
        },
        "handlers.collectDepositRequest": {
            "type": "object",
            "required": [
                "amount",
                "method"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "method": {
                    "$ref": "#/definitions/models.PaymentMethod"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "handlers.confirmDraftInvoiceRequest": {
            "type": "object",
            "required": [
                "electric_new",
                "water_new"
            ],
            "properties": {
                "due_date": {
                    "description": "format: 2006-01-02, để trống giữ nguyên due_date tạm của bản nháp",
                    "type": "string"
                },
                "electric_new": {
                    "type": "number"
                },
                "occupants": {
                    "type": "integer"
                },
                "other_fees": {
                    "type": "number"
                },
                "other_note": {
                    "type": "string"
                },
                "water_new": {
                    "type": "number"
                }
            }
        },
        "handlers.createContractRequest": {
            "type": "object",
            "required": [
                "end_date",
                "room_id",
                "start_date",
                "tenant_ids"
            ],
            "properties": {
                "deposit_amount": {
                    "type": "number",
                    "minimum": 0
                },
                "end_date": {
                    "description": "\"YYYY-MM-DD\"",
                    "type": "string"
                },
                "monthly_rent": {
                    "description": "MonthlyRent: để trống -\u003e lấy theo giá niêm yết hiện tại của phòng.",
                    "type": "number"
                },
                "note": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "start_date": {
                    "description": "\"YYYY-MM-DD\", vd \"2025-07-01\"",
                    "type": "string"
                },
                "tenant_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.createInvoiceRequest": {
            "type": "object",
            "required": [
                "electric_new",
                "month",
                "room_id",
                "water_new",
                "year"
            ],
            "properties": {
                "due_date": {
                    "description": "format: 2006-01-02",
                    "type": "string"
                },
                "electric_new": {
                    "type": "number"
                },
                "electric_old": {
                    "description": "ElectricOld/WaterOld: để trống (null) để hệ thống TỰ ĐỘNG lấy chỉ số mới nhất\n(electric_new/water_new) của hóa đơn gần nhất cùng phòng làm chỉ số cũ tháng này.\nChỉ cần nhập tay khi: hóa đơn đầu tiên của phòng, hoặc vừa thay đồng hồ điện/nước mới.",
                    "type": "number"
                },
                "month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1
                },
                "occupants": {
                    "description": "Occupants: để trống (null) để hệ thống tự lấy số người hiện tại của phòng\n(room.occupants). Chỉ cần nhập tay nếu tháng này số người ở khác với\nsố đang lưu trên phòng (vd: có người mới dọn vào/ra giữa tháng).",
                    "type": "integer"
                },
                "other_fees": {
                    "type": "number"
                },
                "other_note": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "water_new": {
                    "type": "number"
                },
                "water_old": {
                    "type": "number"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "handlers.createPaymentRequest": {
            "type": "object",
            "required": [
                "amount",
                "invoice_id",
                "method"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "invoice_id": {
                    "type": "string"
                },
                "method": {
                    "enum": [
                        "cash",
                        "bank_transfer",
                        "other"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PaymentMethod"
                        }
                    ]
                },
                "note": {
                    "type": "string"
                },
                "paid_at": {
                    "description": "format: 2006-01-02, mặc định là hôm nay",
                    "type": "string"
                }
            }
        },
        "handlers.createRoomRequest": {
            "type": "object",
            "required": [
                "capacity",
                "code",
                "monthly_rent",
                "price_electricity",
                "price_water"
            ],
            "properties": {
                "capacity": {
                    "type": "integer",
                    "minimum": 1
                },
                "code": {
                    "type": "string"
                },
                "floor": {
                    "type": "integer"
                },
                "management_fee_per_person": {
                    "type": "number"
                },
                "monthly_rent": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "occupants": {
                    "type": "integer"
                },
                "price_electricity": {
                    "type": "number"
                },
                "price_water": {
                    "type": "number"
                }
            }
        },
        "handlers.createTenantRequest": {
            "type": "object",
            "required": [
                "full_name",
                "password",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone": {
                    "type": "string"
                },
                "room_id": {
                    "description": "optional lúc tạo, có thể gán phòng sau",
                    "type": "string"
                }
            }
        },
        "handlers.extendContractRequest": {
            "type": "object",
            "required": [
                "new_end_date"
            ],
            "properties": {
                "new_end_date": {
                    "description": "\"YYYY-MM-DD\"",
                    "type": "string"
                },
                "new_monthly_rent": {
                    "description": "để trống = giữ nguyên giá cũ",
                    "type": "number"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "handlers.generateDraftInvoicesRequest": {
            "type": "object",
            "properties": {
                "month": {
                    "description": "Month/Year: để trống -\u003e dùng tháng/năm hiện tại. Chỉ cần truyền khi\nmanager muốn tạo bù cho 1 tháng cụ thể khác tháng hiện tại.",
                    "type": "integer"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "handlers.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string",
                    "x-order": "0"
                },
                "password": {
                    "type": "string",
                    "x-order": "1"
                }
            }
        },
        "handlers.sepayWebhookPayload": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "accumulated": {
                    "type": "number"
                },
                "code": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "gateway": {
                    "type": "string"
                },
                "id": {
                    "description": "ID giao dịch phía SePay, dùng để chống trùng lặp",
                    "type": "integer"
                },
                "referenceCode": {
                    "type": "string"
                },
                "subAccount": {
                    "type": "string"
                },
                "transactionDate": {
                    "type": "string"
                },
                "transferAmount": {
                    "type": "number"
                },
                "transferType": {
                    "description": "\"in\" | \"out\"",
                    "type": "string"
                }
            }
        },
        "handlers.updateContractRequest": {
            "type": "object",
            "properties": {
                "deposit_amount": {
                    "description": "DepositAmount: chỉ cho sửa khi CHƯA thu đồng cọc nào (deposit_paid == 0),\ntránh làm sai lệch deposit_status đã tính dựa trên số đã thu.",
                    "type": "number",
                    "minimum": 0
                },
                "monthly_rent": {
                    "type": "number"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "handlers.updateInvoiceRequest": {
            "type": "object",
            "properties": {
                "due_date": {
                    "description": "format: 2006-01-02",
                    "type": "string"
                },
                "electric_new": {
                    "type": "number"
                },
                "occupants": {
                    "type": "integer"
                },
                "other_fees": {
                    "type": "number"
                },
                "other_note": {
                    "type": "string"
                },
                "water_new": {
                    "type": "number"
                }
            }
        },
        "handlers.updatePaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "method": {
                    "enum": [
                        "cash",
                        "bank_transfer",
                        "other"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PaymentMethod"
                        }
                    ]
                },
                "note": {
                    "type": "string"
                },
                "paid_at": {
                    "description": "format: 2006-01-02",
                    "type": "string"
                }
            }
        },
        "handlers.updateRoomRequest": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer",
                    "minimum": 1
                },
                "floor": {
                    "type": "integer"
                },
                "management_fee_per_person": {
                    "type": "number"
                },
                "monthly_rent": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "note": {
                    "type": "string"
                },
                "occupants": {
                    "type": "integer"
                },
                "price_electricity": {
                    "type": "number"
                },
                "price_water": {
                    "type": "number"
                },
                "status": {
                    "enum": [
                        "available",
                        "occupied"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.RoomStatus"
                        }
                    ]
                }
            }
        },
        "handlers.updateTenantRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                }
            }
        },
        "models.PaymentMethod": {
            "type": "string",
            "enum": [
                "cash",
                "bank_transfer",
                "other"
            ],
            "x-enum-varnames": [
                "PaymentMethodCash",
                "PaymentMethodTransfer",
                "PaymentMethodOther"
            ]
        },
        "models.RoomStatus": {
            "type": "string",
            "enum": [
                "available",
                "occupied"
            ],
            "x-enum-varnames": [
                "RoomStatusAvailable",
                "RoomStatusOccupied"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Dán trực tiếp giá trị token vào đây (không cần gõ \"Bearer \" phía trước, server tự nhận diện cả 2 dạng)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "RUMA Backend API",
	Description:      "API quản lý nhà trọ: phòng, người thuê, hóa đơn, thanh toán.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
